services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: songsdb
    ports:
      - '5440:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back-end/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./back-end
    container_name: backend_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/songsdb?sslmode=disable
    ports:
      - '8888:8080'
    volumes:
      - ./back-end/migrations:/app/migrations

  frontend:
    build:
      context: ./front-end
    container_name: frontend_app
    ports:
      - '9999:80'

volumes:
  postgres_data:
